### PR TITLE
Actions menu and download pop-up improvements

### PR DESCRIPTION
**Pull request by PhilippKosarev**
## Before
Screenshot From 2024-12-10 23-18-56

## After
Screenshot From 2024-12-10 23-26-44

## Issues
GtkComboBoxText doesn't seem to have any way of ellipsizing its contents, which can look quite comical with long paths. GtkDropDown or AdwComboRow might solve this, but I'm not good with rust so not sure how to do that.
Screenshot From 2024-12-10 23-48-16

GtkComboBoxText is also misplaced until an item is selected, afaik GtkDropDown and AdwComboRow don't have this problem.
image

Local files row for some reason has a clickable element, even though it's just a GtkBox.
image

All of the actions now do the same thing, but the code doesn't reflect that because I'm not sure how to fix that without crashing the app.
image

`download_item.rs` is also quite messy :P

### CODE REVIEW

**Comment by Catley94** [comment]
I like this! It goes well with some changes that I also made and about to do a PR for. I am also not a rust expert, I've just picked away at a few bits to make it look a little cleaner.

**Comment by aknarts** [comment]
The entire download process is quite messy but that is mostly because the entire download process from Epics side is quite messy... 

It needs a major rework as to not bind the UI to the download but instead download it in a separate thread and update the UI accordingly... I know who wrote it that way and I beat him daily :D.

**Comment by PhilippKosarev** [comment]
So I've experimented a bit with how the assets look, and got this
Screenshot From 2024-12-25 00-03-08
 I personally find it more readable and easier to understand at a glance, while being more space effecient. What do you think?

Here's how it looked before for reference
Screenshot From 2024-12-24 23-55-16

**Comment by PhilippKosarev** [comment]
Also, happy Christmas!

**Comment by Catley94** [comment]
Happy Christmas to you too :)

**Comment by PhilippKosarev** [comment]
The commit [8ffa1df](https://github.com/AchetaGames/Epic-Asset-Manager/pull/300/commits/8ffa1df8832b92524f2d89a88516a8f05b4ab8eb):
- Fixes the details panel not closing in every tab (using `set_visible(false)`)
- Makes small tweaks to the Preferences window
- Changes the asset styling as seen in the previous comment
- Uses more css classes instead of markup for consistency
- Changes how the sidebar looks
- Improves the Docker UE download tab
- Uses AdwAvatar instead of GtkImage in every tab

**Comment by PhilippKosarev** [comment]
<details><summary>Here are some images</summary>

library

projects

engines

directories

github

</details>

**Comment by Catley94** [comment]
> Here are some images

Love it!

**Review by mistastn — APPROVED** [review]

**Review by aknarts — APPROVED** [review]

**Comment by aknarts** [comment]
I constantly forget to switch to the correct account... :/

**Pull request merged**
