### PR TITLE
Major Rewrite

### PR DESCRIPTION
**Pull request by aknarts**
While everyone is eager to get the FAB part working I need to first rewrite the app to use the current GTK crate, I have been putting this off for various reasons but I think I am on a good track. 

The FAB support will come as part of this, but I expect this to take a bit. At the same time I will try to dedicate some time every day to finish this in some reasonable time.

### CODE REVIEW

**Comment by PhilippKosarev** [comment]
Hey, thank you so much for starting work on this.
Glad to hear that FAB support is in the scope, will it be as painstakingly reverse engineered as the unreal marketplace, or does FAB have a real API?
Also, would it be appropriate to submit PRs right now, or is it better to wait until the dependencies are updated?

**Comment by aknarts** [comment]
> Hey, thank you so much for starting work on this. Glad to hear that FAB support is in the scope, will it be as painstakingly reverse engineered as the unreal marketplace, or does FAB have a real API? Also, would it be appropriate to submit PRs right now, or is it better to wait until the dependencies are updated?

FAB has some API, it is still MITM work but it looks better compared to what had to be done with the general Marketplace API. Plus it is essentially 3 API calls to get to data I need to reuse code that already exists.

As for the PRs... feel free to create them you are doing mostly xml changes and I am not touching that and will not at the moment. But keep in mind that the Asset library and asset details will change as a result of the rewrite.

**Comment by aknarts** [comment]
This should now technically compile. Not saying it works, but it should compile... No FAB work in it yet.

**Comment by PhilippKosarev** [comment]
Alright, sounds great. Looks like it's a lot of work, so I'm happy to hear it's going well :)
Will open a PR for you to check out.

**Comment by aknarts** [comment]
@PhilippKosarev  Would you be able to test this build? It should have all your changes included and is updated to the latest GTK version. For me it seems to run just fine. There are still some issues from your changes(like the details panel not closing) So if you run into them note them here and I will fix them.

**Comment by PhilippKosarev** [comment]
Yeah, this builds and works for me, the new custom adwaita accents work as well.
As for my changes, there's the sidebar button which I prefixed to the header bar. It needs to be visible only in the library tab and connected to expanding the sidebar instead of the existing `expand_button`, which needs to be removed.
Also the logs look a bit out of place.
image
The panel not closing might be difficult to track down, so giving it a transition like `slide-right` could be a temporary fix.

**Comment by aknarts** [comment]
As this works I will be merging this now. Just so I can separate the FAB work and fixes/improvements. This will not be a release but will live in the main branch.

**Pull request merged**
