### PR TITLE
Improved projects tab ui

### PR DESCRIPTION
**Pull request by PhilippKosarev**
## Before:
old

## After:
new

### CODE REVIEW

**Comment by PhilippKosarev** [comment]
Yeah, the new Open log button opens the folder with the log selected which I find most useful and it simplifies the experience a bit. I understand if you think it intrudes on the functionality though, so I can bring the other button back if you want.
The Launch button does take up quite a bit of space, but that is 80%+ of what you will be pressing on the Projects page so I think it's justified. Let me know if you think otherwise though.

**Review by Nightmare1984 — COMMENTED** [review]
It's good But The Right Side Panel Need's To Be A Toggle And Not A Forced Side Panel Suggestion is To make The Right Side Panel Toggle A Option  If People Won't To Disable It Or Turn It On

**Comment by PhilippKosarev** [comment]
@Nightmare1984, If I understand you correctly (almost had a stroke reading that), you are concerned about the close button on the sidebar not properly functioning. If so then this has been discussed [here](https://github.com/AchetaGames/Epic-Asset-Manager/pull/282#issuecomment-2393969615), and it is not the intention to leave it as is.

**Comment by Nightmare1984** [comment]
Sorry For Being Asshole About That i Should Have Looked Merged PR's But After Reading That Merged PR Look's Really Good

**Review by aknarts — APPROVED** [review]

**Pull request merged**
