### PR TITLE
Changes to styling of assets list and details pane.

### PR DESCRIPTION
**Pull request by Catley94**
Just a few changes that hopefully you think look a little cleaner. 

Spaced out the assets a little, giving them breathing room.

Before:
Epic Asset Manager - Assets_Before

After:
Epic Asset Manager - Assets_After

Moved title / name of asset with the details of the asset below image.

Before:
Epic Asset Manager - Details_Before

After:
Epic Asset Manager - Details_After

### CODE REVIEW

**Comment by PhilippKosarev** [comment]
Hey, just here to say that it appears you've done your changes quite a while ago now.
The asset title being below the images might not work as well with all the changes I've made to the UI recently.
I would recommend building main first to see the changes to the UI and check if they might interfere with your commits.
And then merge or rebase from main.
✌️

**Comment by Catley94** [comment]
Thanks! No worries, I will do that. ☺️

**Comment by aknarts** [comment]
I would also hold of on this view alltogether... while I will adopt some of the code for the FAB view it will get some major rework.

**Comment by Catley94** [comment]
No worries, it gives me time to learn a bit more rust and play around with gtk-rs binding:)

**Comment by Catley94** [comment]
> Hey, just here to say that it appears you've done your changes quite a while ago now. The asset title being below the images might not work as well with all the changes I've made to the UI recently. I would recommend building main first to see the changes to the UI and check if they might interfere with your commits. And then merge or rebase from main. ✌️

I really like the changes you've made to the UI and anyone else that contributed, it's looking much cleaner :-)

**Pull request closed without merging**
